language: python

jobs:
  include:
    - stage: check
      name: "Syntax validation - Python 3.8"
      python: 3.8
      script:
         - python3 -m compileall -q i19-gui/*

    - name: "Flake8 - Python 3.8"
      python: 3.8
      script: .travis/run-flake8
      if: type = pull_request
